# Big Clock
import board
import neopixel
import time
import datetime

brightness = (10, 0, 0)

pixels = neopixel.NeoPixel(board.D18, 86)

# minutes
def digitOne(number, color):
    display = number
    
    if display == 0:
        pixels[5] = (color)
        pixels[4] = (color)
        pixels[3] = (color)
        pixels[2] = (color)
        pixels[1] = (color)
        pixels[0] = (color)
        pixels[6] = (color)
        pixels[7] = (color)
        pixels[8] = (color)
        pixels[9] = (color)
        pixels[10] = (color)
        pixels[11] = (color)
        pixels[12] = (color)
        pixels[13] = (color)
        pixels[14] = (color)
        pixels[15] = (color)
        pixels[16] = (color)
        pixels[17] = (color)
        pixels[20] = (0, 0, 0)
        pixels[19] = (0, 0, 0)
        pixels[18] = (0, 0, 0)
        pixels.show()
        
    elif display == 1:
        pixels[0] = (color)
        pixels[1] = (color)
        pixels[2] = (color)
        pixels[15] = (color)
        pixels[16] = (color)
        pixels[17] = (color)
        pixels[5] = (0, 0, 0)
        pixels[4] = (0, 0, 0)
        pixels[3] = (0, 0, 0)
        pixels[6] = (0, 0, 0)
        pixels[7] = (0, 0, 0)
        pixels[8] = (0, 0, 0)
        pixels[20] = (0, 0, 0)
        pixels[19] = (0, 0, 0)
        pixels[18] = (0, 0, 0)
        pixels[9] = (0, 0, 0)
        pixels[10] = (0, 0, 0)
        pixels[11] = (0, 0, 0)
        pixels[12] = (0, 0, 0)
        pixels[13] = (0, 0, 0)
        pixels[14] = (0, 0, 0)
        pixels.show()
        
    elif display == 2:
        pixels[5] = (color)
        pixels[4] = (color)
        pixels[3] = (color)
        pixels[2] = (color)
        pixels[1] = (color)
        pixels[0] = (color)
        pixels[18] = (color)
        pixels[19] = (color)
        pixels[20] = (color)
        pixels[9] = (color)
        pixels[10] = (color)
        pixels[11] = (color)
        pixels[12] = (color)
        pixels[13] = (color)
        pixels[14] = (color)
        pixels[6] = (0, 0, 0)
        pixels[7] = (0, 0, 0)
        pixels[8] = (0, 0, 0)
        pixels[17] = (0, 0, 0)
        pixels[16] = (0, 0, 0)
        pixels[15] = (0, 0, 0)
        pixels.show()

    elif display == 3:
        pixels[5] = (color)
        pixels[4] = (color)
        pixels[3] = (color)
        pixels[2] = (color)
        pixels[1] = (color)
        pixels[0] = (color)
        pixels[20] = (color)
        pixels[19] = (color)
        pixels[18] = (color)
        pixels[17] = (color)
        pixels[16] = (color)
        pixels[15] = (color)
        pixels[14] = (color)
        pixels[13] = (color)
        pixels[12] = (color)
        pixels[6] = (0, 0, 0)
        pixels[7] = (0, 0, 0)
        pixels[8] = (0, 0, 0)
        pixels[9] = (0, 0, 0)
        pixels[10] = (0, 0, 0)
        pixels[11] = (0, 0, 0)
        pixels.show()
        
    elif display == 4:
        pixels[6] = (color)
        pixels[7] = (color)
        pixels[8] = (color)
        pixels[20] = (color)
        pixels[19] = (color)
        pixels[18] = (color)
        pixels[2] = (color)
        pixels[1] = (color)
        pixels[0] = (color)
        pixels[17] = (color)
        pixels[16] = (color)
        pixels[15] = (color)
        pixels[5] = (0, 0, 0)
        pixels[4] = (0, 0, 0)
        pixels[3] = (0, 0, 0)
        pixels[9] = (0, 0, 0)
        pixels[10] = (0, 0, 0)
        pixels[11] = (0, 0, 0)
        pixels[12] = (0, 0, 0)
        pixels[13] = (0, 0, 0)
        pixels[14] = (0, 0, 0)
        pixels.show()

    elif display == 5:
        pixels[3] = (color)
        pixels[4] = (color)
        pixels[5] = (color)
        pixels[6] = (color)
        pixels[7] = (color)
        pixels[8] = (color)
        pixels[20] = (color)
        pixels[19] = (color)
        pixels[18] = (color)
        pixels[17] = (color)
        pixels[16] = (color)
        pixels[15] = (color)
        pixels[14] = (color)
        pixels[13] = (color)
        pixels[12] = (color)
        pixels[2] = (0, 0, 0)
        pixels[1] = (0, 0, 0)
        pixels[0] = (0, 0, 0)
        pixels[9] = (0, 0, 0)
        pixels[10] = (0, 0, 0)
        pixels[11] = (0, 0, 0)
        pixels.show()

    elif display == 6:
        pixels[5] = (color)
        pixels[4] = (color)
        pixels[3] = (color)
        pixels[6] = (color)
        pixels[7] = (color)
        pixels[8] = (color)
        pixels[20] = (color)
        pixels[19] = (color)
        pixels[18] = (color)
        pixels[17] = (color)
        pixels[16] = (color)
        pixels[15] = (color)
        pixels[14] = (color)
        pixels[13] = (color)
        pixels[12] = (color)
        pixels[11] = (color)
        pixels[10] = (color)
        pixels[9] = (color)
        pixels[2] = (0, 0, 0)
        pixels[1] = (0, 0, 0)
        pixels[0] = (0, 0, 0)
        pixels.show()

    elif display == 7:
        pixels[5] = (color)
        pixels[4] = (color)
        pixels[3] = (color)
        pixels[2] = (color)
        pixels[1] = (color)
        pixels[0] = (color)
        pixels[17] = (color)
        pixels[16] = (color)
        pixels[15] = (color)
        pixels[6] = (0, 0, 0)
        pixels[7] = (0, 0, 0)
        pixels[8] = (0, 0, 0)
        pixels[20] = (0, 0, 0)
        pixels[19] = (0, 0, 0)
        pixels[18] = (0, 0, 0)
        pixels[9] = (0, 0, 0)
        pixels[10] = (0, 0, 0)
        pixels[11] = (0, 0, 0)
        pixels[12] = (0, 0, 0)
        pixels[13] = (0, 0, 0)
        pixels[14] = (0, 0, 0)
        pixels.show()

    elif display == 8:
        pixels[5] = (color)
        pixels[4] = (color)
        pixels[3] = (color)
        pixels[2] = (color)
        pixels[1] = (color)
        pixels[0] = (color)
        pixels[6] = (color)
        pixels[7] = (color)
        pixels[8] = (color)
        pixels[20] = (color)
        pixels[19] = (color)
        pixels[18] = (color)
        pixels[9] = (color)
        pixels[10] = (color)
        pixels[11] = (color)
        pixels[12] = (color)
        pixels[13] = (color)
        pixels[14] = (color)
        pixels[15] = (color)
        pixels[16] = (color)
        pixels[17] = (color)
        pixels.show()

    elif display == 9:
        pixels[5] = (color)
        pixels[4] = (color)
        pixels[3] = (color)
        pixels[2] = (color)
        pixels[1] = (color)
        pixels[0] = (color)
        pixels[6] = (color)
        pixels[7] = (color)
        pixels[8] = (color)
        pixels[20] = (color)
        pixels[19] = (color)
        pixels[18] = (color)
        pixels[12] = (color)
        pixels[13] = (color)
        pixels[14] = (color)
        pixels[15] = (color)
        pixels[16] = (color)
        pixels[17] = (color)
        pixels[9] = (0, 0, 0)
        pixels[10] = (0, 0, 0)
        pixels[11] = (0, 0, 0)
        pixels.show()

# minutes again
def digitTwo(number, color):   
    if number == 0:
        pixels[26] = (color)
        pixels[25] = (color)
        pixels[24] = (color)
        pixels[23] = (color)
        pixels[22] = (color)
        pixels[21] = (color)
        pixels[33] = (color)
        pixels[34] = (color)
        pixels[35] = (color)
        pixels[36] = (color)
        pixels[37] = (color)
        pixels[38] = (color)
        pixels[39] = (color)
        pixels[40] = (color)
        pixels[41] = (color)
        pixels[29] = (color)
        pixels[28] = (color)
        pixels[27] = (color)
        pixels[30] = (0, 0, 0)
        pixels[31] = (0, 0, 0)
        pixels[32] = (0, 0, 0)
        pixels.show()

    elif number == 1:
        pixels[23] = (color)
        pixels[22] = (color)
        pixels[21] = (color)
        pixels[33] = (color)
        pixels[34] = (color)
        pixels[35] = (color)
        pixels[24] = (0, 0, 0)
        pixels[25] = (0, 0, 0)
        pixels[26] = (0, 0, 0)
        pixels[27] = (0, 0, 0)
        pixels[28] = (0, 0, 0)
        pixels[29] = (0, 0, 0)
        pixels[30] = (0, 0, 0)
        pixels[31] = (0, 0, 0)
        pixels[32] = (0, 0, 0)
        pixels[41] = (0, 0, 0)
        pixels[40] = (0, 0, 0)
        pixels[39] = (0, 0, 0)
        pixels[38] = (0, 0, 0)
        pixels[37] = (0, 0, 0)
        pixels[36] = (0, 0, 0)
        pixels.show()

    elif number == 2:
        pixels[26] = (color)
        pixels[25] = (color)
        pixels[24] = (color)
        pixels[23] = (color)
        pixels[22] = (color)
        pixels[21] = (color)
        pixels[32] = (color)
        pixels[31] = (color)
        pixels[30] = (color)
        pixels[41] = (color)
        pixels[40] = (color)
        pixels[39] = (color)
        pixels[38] = (color)
        pixels[37] = (color)
        pixels[36] = (color)
        pixels[27] = (0, 0, 0)
        pixels[28] = (0, 0, 0)
        pixels[29] = (0, 0, 0)
        pixels[33] = (0, 0, 0)
        pixels[34] = (0, 0, 0)
        pixels[35] = (0, 0, 0)
        pixels.show()
    
    elif number == 3:
        pixels[26] = (color)
        pixels[25] = (color)
        pixels[24] = (color)
        pixels[23] = (color)
        pixels[22] = (color)
        pixels[21] = (color)
        pixels[30] = (color)
        pixels[31] = (color)
        pixels[32] = (color)
        pixels[33] = (color)
        pixels[34] = (color)
        pixels[35] = (color)
        pixels[36] = (color)
        pixels[37] = (color)
        pixels[38] = (color)
        pixels[27] = (0, 0, 0)
        pixels[28] = (0, 0, 0)
        pixels[29] = (0, 0, 0)
        pixels[41] = (0, 0, 0)
        pixels[40] = (0, 0, 0)
        pixels[39] = (0, 0, 0)
        pixels.show()
    
    elif number == 4:
        pixels[27] = (color)
        pixels[28] = (color)
        pixels[29] = (color)
        pixels[30] = (color)
        pixels[31] = (color)
        pixels[32] = (color)
        pixels[23] = (color)
        pixels[22] = (color)
        pixels[21] = (color)
        pixels[33] = (color)
        pixels[34] = (color)
        pixels[35] = (color)
        pixels[26] = (0, 0, 0)
        pixels[25] = (0, 0, 0)
        pixels[24] = (0, 0, 0)
        pixels[41] = (0, 0, 0)
        pixels[40] = (0, 0, 0)
        pixels[39] = (0, 0, 0)
        pixels[38] = (0, 0, 0)
        pixels[37] = (0, 0, 0)
        pixels[36] = (0, 0, 0)
        pixels.show()
    
    elif number == 5:
        pixels[24] = (color)
        pixels[25] = (color)
        pixels[26] = (color)
        pixels[27] = (color)
        pixels[28] = (color)
        pixels[29] = (color)
        pixels[30] = (color)
        pixels[31] = (color)
        pixels[32] = (color)
        pixels[33] = (color)
        pixels[34] = (color)
        pixels[35] = (color)
        pixels[36] = (color)
        pixels[37] = (color)
        pixels[38] = (color)
        pixels[23] = (0, 0, 0)
        pixels[22] = (0, 0, 0)
        pixels[21] = (0, 0, 0)
        pixels[41] = (0, 0, 0)
        pixels[40] = (0, 0, 0)
        pixels[39] = (0, 0, 0)
        pixels.show()
    
    elif number == 6:
        pixels[24] = (color)
        pixels[25] = (color)
        pixels[26] = (color)
        pixels[27] = (color)
        pixels[28] = (color)
        pixels[29] = (color)
        pixels[41] = (color)
        pixels[40] = (color)
        pixels[39] = (color)
        pixels[38] = (color)
        pixels[37] = (color)
        pixels[36] = (color)
        pixels[35] = (color)
        pixels[34] = (color)
        pixels[33] = (color)
        pixels[32] = (color)
        pixels[31] = (color)
        pixels[30] = (color)
        pixels.show()

    elif number == 7:
        pixels[24] = (color)
        pixels[25] = (color)
        pixels[26] = (color)
        pixels[23] = (color)
        pixels[22] = (color)
        pixels[21] = (color)
        pixels[33] = (color)
        pixels[34] = (color)
        pixels[35] = (color)
        pixels[27] = (0, 0, 0)
        pixels[28] = (0, 0, 0)
        pixels[29] = (0, 0, 0)
        pixels[30] = (0, 0, 0)
        pixels[31] = (0, 0, 0)
        pixels[32] = (0, 0, 0)
        pixels[41] = (0, 0, 0)
        pixels[40] = (0, 0, 0)
        pixels[39] = (0, 0, 0)
        pixels[38] = (0, 0, 0)
        pixels[37] = (0, 0, 0)
        pixels[36] = (0, 0, 0)
        pixels.show()
    
    elif number == 8:
        pixels[21] = (color)
        pixels[22] = (color)
        pixels[23] = (color)
        pixels[24] = (color)
        pixels[25] = (color)
        pixels[26] = (color)
        pixels[27] = (color)
        pixels[28] = (color)
        pixels[29] = (color)
        pixels[30] = (color)
        pixels[31] = (color)
        pixels[32] = (color)
        pixels[33] = (color)
        pixels[34] = (color)
        pixels[35] = (color)
        pixels[36] = (color)
        pixels[37] = (color)
        pixels[38] = (color)
        pixels[39] = (color)
        pixels[40] = (color)
        pixels[41] = (color)
        
    elif number == 9:
        pixels[21] = (color)
        pixels[22] = (color)
        pixels[23] = (color)
        pixels[24] = (color)
        pixels[25] = (color)
        pixels[26] = (color)
        pixels[27] = (color)
        pixels[28] = (color)
        pixels[29] = (color)
        pixels[30] = (color)
        pixels[31] = (color)
        pixels[32] = (color)
        pixels[36] = (color)
        pixels[37] = (color)
        pixels[38] = (color)
        pixels[35] = (color)
        pixels[34] = (color)
        pixels[33] = (color)
        pixels[41] = (0, 0, 0)
        pixels[40] = (0, 0, 0)
        pixels[39] = (0, 0, 0)
        pixels.show()

# hours
def digitThree(number, color):
    if number == 0:
        pixels[44] = (color)
        pixels[45] = (color)
        pixels[46] = (color)
        pixels[47] = (color)
        pixels[48] = (color)
        pixels[49] = (color)
        pixels[50] = (color)
        pixels[51] = (color)
        pixels[52] = (color)
        pixels[56] = (color)
        pixels[57] = (color)
        pixels[58] = (color)
        pixels[59] = (color)
        pixels[60] = (color)
        pixels[61] = (color)
        pixels[62] = (color)
        pixels[63] = (color)
        pixels[64] = (color)
        pixels[53] = (0, 0, 0)
        pixels[54] = (0, 0, 0)
        pixels[55] = (0, 0, 0)
        pixels.show()

    elif number == 1:
        pixels[46] = (color)
        pixels[45] = (color)
        pixels[44] = (color)
        pixels[56] = (color)
        pixels[57] = (color)
        pixels[58] = (color)
        pixels[47] = (0, 0, 0)
        pixels[48] = (0, 0, 0)
        pixels[49] = (0, 0, 0)
        pixels[50] = (0, 0, 0)
        pixels[51] = (0, 0, 0)
        pixels[52] = (0, 0, 0)
        pixels[53] = (0, 0, 0)
        pixels[54] = (0, 0, 0)
        pixels[55] = (0, 0, 0)
        pixels[59] = (0, 0, 0)
        pixels[60] = (0, 0, 0)
        pixels[61] = (0, 0, 0)
        pixels[62] = (0, 0, 0)
        pixels[63] = (0, 0, 0)
        pixels[64] = (0, 0, 0)
        pixels.show()

    elif number == 2:
        pixels[49] = (color)
        pixels[48] = (color)
        pixels[47] = (color)
        pixels[46] = (color)
        pixels[45] = (color)
        pixels[44] = (color)
        pixels[53] = (color)
        pixels[54] = (color)
        pixels[55] = (color)
        pixels[64] = (color)
        pixels[63] = (color)
        pixels[62] = (color)
        pixels[61] = (color)
        pixels[60] = (color)
        pixels[59] = (color)
        pixels[56] = (0, 0, 0)
        pixels[57] = (0, 0, 0)
        pixels[58] = (0, 0, 0)
        pixels[50] = (0, 0, 0)
        pixels[51] = (0, 0, 0)
        pixels[52] = (0, 0, 0)
        pixels.show()

    elif number == 3:
        pixels[49] = (color)
        pixels[48] = (color)
        pixels[47] = (color)
        pixels[46] = (color)
        pixels[45] = (color)
        pixels[44] = (color)
        pixels[53] = (color)
        pixels[54] = (color)
        pixels[55] = (color)
        pixels[56] = (color)
        pixels[57] = (color)
        pixels[58] = (color)
        pixels[59] = (color)
        pixels[60] = (color)
        pixels[61] = (color)
        pixels[62] = (0, 0, 0)
        pixels[63] = (0, 0, 0)
        pixels[64] = (0, 0, 0)
        pixels[50] = (0, 0, 0)
        pixels[51] = (0, 0, 0)
        pixels[52] = (0, 0, 0)
        pixels.show()

    elif number == 4:
        pixels[50] = (color)
        pixels[51] = (color)
        pixels[52] = (color)
        pixels[53] = (color)
        pixels[54] = (color)
        pixels[55] = (color)
        pixels[56] = (color)
        pixels[57] = (color)
        pixels[58] = (color)
        pixels[46] = (color)
        pixels[45] = (color)
        pixels[44] = (color)
        pixels[49] = (0, 0, 0)
        pixels[48] = (0, 0, 0)
        pixels[47] = (0, 0, 0)
        pixels[64] = (0, 0, 0)
        pixels[63] = (0, 0, 0)
        pixels[62] = (0, 0, 0)
        pixels[61] = (0, 0, 0)
        pixels[60] = (0, 0, 0)
        pixels[59] = (0, 0, 0)
        pixels.show()
    
    elif number == 5:
        pixels[47] = (color)
        pixels[48] = (color)
        pixels[49] = (color)
        pixels[50] = (color)
        pixels[51] = (color)
        pixels[52] = (color)
        pixels[53] = (color)
        pixels[54] = (color)
        pixels[55] = (color)
        pixels[56] = (color)
        pixels[57] = (color)
        pixels[58] = (color)
        pixels[59] = (color)
        pixels[60] = (color)
        pixels[61] = (color)
        pixels[62] = (0, 0, 0)
        pixels[63] = (0, 0, 0)
        pixels[64] = (0, 0, 0)
        pixels[46] = (0, 0, 0)
        pixels[45] = (0, 0, 0)
        pixels[44] = (0, 0, 0)
        pixels.show()

    elif number == 6:
        pixels[47] = (color)
        pixels[48] = (color)
        pixels[49] = (color)
        pixels[50] = (color)
        pixels[51] = (color)
        pixels[52] = (color)
        pixels[53] = (color)
        pixels[54] = (color)
        pixels[55] = (color)
        pixels[56] = (color)
        pixels[57] = (color)
        pixels[58] = (color)
        pixels[59] = (color)
        pixels[60] = (color)
        pixels[61] = (color)
        pixels[62] = (color)
        pixels[63] = (color)
        pixels[64] = (color)
        pixels[44] = (0, 0, 0)
        pixels[45] = (0, 0, 0)
        pixels[46] = (0, 0, 0)
        pixels.show()

    elif number == 7:
        pixels[44] = (color)
        pixels[45] = (color)
        pixels[46] = (color)
        pixels[47] = (color)
        pixels[48] = (color)
        pixels[49] = (color)
        pixels[59] = (color)
        pixels[57] = (color)
        pixels[58] = (color)
        pixels[50] = (0, 0, 0)
        pixels[51] = (0, 0, 0)
        pixels[52] = (0, 0, 0)
        pixels[53] = (0, 0, 0)
        pixels[54] = (0, 0, 0)
        pixels[55] = (0, 0, 0)
        pixels[59] = (0, 0, 0)
        pixels[60] = (0, 0, 0)
        pixels[61] = (0, 0, 0)
        pixels[62] = (0, 0, 0)
        pixels[63] = (0, 0, 0)
        pixels[64] = (0, 0, 0)
        pixels.show()

    elif number == 8:
        pixels[44] = (color)
        pixels[45] = (color)
        pixels[46] = (color)
        pixels[47] = (color)
        pixels[48] = (color)
        pixels[49] = (color)
        pixels[50] = (color)
        pixels[51] = (color)
        pixels[52] = (color)
        pixels[53] = (color)
        pixels[54] = (color)
        pixels[55] = (color)
        pixels[56] = (color)
        pixels[57] = (color)
        pixels[58] = (color)
        pixels[59] = (color)
        pixels[60] = (color)
        pixels[61] = (color)
        pixels[62] = (color)
        pixels[63] = (color)
        pixels[64] = (color)
        pixels.show()
        
    elif number == 9:
        pixels[44] = (color)
        pixels[45] = (color)
        pixels[46] = (color)
        pixels[47] = (color)
        pixels[48] = (color)
        pixels[49] = (color)
        pixels[50] = (color)
        pixels[51] = (color)
        pixels[52] = (color)
        pixels[53] = (color)
        pixels[54] = (color)
        pixels[55] = (color)
        pixels[56] = (color)
        pixels[57] = (color)
        pixels[58] = (color)
        pixels[59] = (color)
        pixels[60] = (color)
        pixels[61] = (color)
        pixels[62] = (0, 0, 0)
        pixels[63] = (0, 0, 0)
        pixels[64] = (0, 0, 0)
        pixels.show()

# hours again
def digitFour(number, color):
    if number == 0:
        pixels[70] = (color)
        pixels[69] = (color)
        pixels[68] = (color)
        pixels[67] = (color)
        pixels[66] = (color)
        pixels[65] = (color)
        pixels[71] = (color)
        pixels[72] = (color)
        pixels[73] = (color)
        pixels[80] = (color)
        pixels[81] = (color)
        pixels[82] = (color)
        pixels[83] = (color)
        pixels[84] = (color)
        pixels[85] = (color)
        pixels[77] = (color)
        pixels[78] = (color)
        pixels[79] = (color)
        pixels[74] = (0, 0, 0)
        pixels[75] = (0, 0, 0)
        pixels[76] = (0, 0, 0)
        pixels.show()

    elif number == 1:
        pixels[65] = (color)
        pixels[66] = (color)
        pixels[67] = (color)
        pixels[77] = (color)
        pixels[78] = (color)
        pixels[79] = (color)
        pixels[74] = (0, 0, 0)
        pixels[75] = (0, 0, 0)
        pixels[76] = (0, 0, 0)
        pixels[80] = (0, 0, 0)
        pixels[81] = (0, 0, 0)
        pixels[82] = (0, 0, 0)
        pixels[83] = (0, 0, 0)
        pixels[84] = (0, 0, 0)
        pixels[85] = (0, 0, 0)
        pixels[73] = (0, 0, 0)
        pixels[72] = (0, 0, 0)
        pixels[71] = (0, 0, 0)
        pixels[70] = (0, 0, 0)
        pixels[68] = (0, 0, 0)
        pixels[69] = (0, 0, 0)
        pixels.show()

    elif number == 2:
        pixels[70] = (color)
        pixels[69] = (color)
        pixels[68] = (color)
        pixels[67] = (color)
        pixels[66] = (color)
        pixels[65] = (color)
        pixels[76] = (color)
        pixels[75] = (color)
        pixels[74] = (color)
        pixels[85] = (color)
        pixels[84] = (color)
        pixels[83] = (color)
        pixels[82] = (color)
        pixels[81] = (color)
        pixels[80] = (color)
        pixels[77] = (0, 0, 0)
        pixels[78] = (0, 0, 0)
        pixels[79] = (0, 0, 0)
        pixels[71] = (0, 0, 0)
        pixels[72] = (0, 0, 0)
        pixels[73] = (0, 0, 0)
        pixels.show()

    elif number == 3:
        pixels[70] = (color)
        pixels[69] = (color)
        pixels[68] = (color)
        pixels[67] = (color)
        pixels[66] = (color)
        pixels[65] = (color)
        pixels[74] = (color)
        pixels[75] = (color)
        pixels[76] = (color)
        pixels[77] = (color)
        pixels[78] = (color)
        pixels[79] = (color)
        pixels[80] = (color)
        pixels[81] = (color)
        pixels[82] = (color)
        pixels[85] = (0, 0, 0)
        pixels[84] = (0, 0, 0)
        pixels[83] = (0, 0, 0)
        pixels[71] = (0, 0, 0)
        pixels[72] = (0, 0, 0)
        pixels[73] = (0, 0, 0)
        pixels.show()

    elif number == 4:
        pixels[71] = (color)
        pixels[72] = (color)
        pixels[73] = (color)
        pixels[74] = (color)
        pixels[75] = (color)
        pixels[76] = (color)
        pixels[77] = (color)
        pixels[78] = (color)
        pixels[79] = (color)
        pixels[65] = (color)
        pixels[66] = (color)
        pixels[67] = (color)
        pixels[68] = (0, 0, 0)
        pixels[69] = (0, 0, 0)
        pixels[70] = (0, 0, 0)
        pixels[85] = (0, 0, 0)
        pixels[84] = (0, 0, 0)
        pixels[83] = (0, 0, 0)
        pixels[82] = (0, 0, 0)
        pixels[81] = (0, 0, 0)
        pixels[80] = (0, 0, 0)
        pixels.show()
    
    elif number == 5:
        pixels[68] = (color)
        pixels[69] = (color)
        pixels[70] = (color)
        pixels[71] = (color)
        pixels[72] = (color)
        pixels[73] = (color)
        pixels[74] = (color)
        pixels[75] = (color)
        pixels[76] = (color)
        pixels[77] = (color)
        pixels[78] = (color)
        pixels[79] = (color)
        pixels[80] = (color)
        pixels[81] = (color)
        pixels[82] = (color)
        pixels[85] = (0, 0, 0)
        pixels[84] = (0, 0, 0)
        pixels[83] = (0, 0, 0)
        pixels[67] = (0, 0, 0)
        pixels[66] = (0, 0, 0)
        pixels[65] = (0, 0, 0)
        pixels.show()

    elif number == 6:
        pixels[68] = (color)
        pixels[69] = (color)
        pixels[70] = (color)
        pixels[71] = (color)
        pixels[72] = (color)
        pixels[73] = (color)
        pixels[74] = (color)
        pixels[75] = (color)
        pixels[76] = (color)
        pixels[77] = (color)
        pixels[78] = (color)
        pixels[79] = (color)
        pixels[80] = (color)
        pixels[81] = (color)
        pixels[82] = (color)
        pixels[83] = (color)
        pixels[84] = (color)
        pixels[85] = (color)
        pixels[65] = (0, 0, 0)
        pixels[66] = (0, 0, 0)
        pixels[67] = (0, 0, 0)
        pixels.show()

    elif number == 7:
        pixels[65] = (color)
        pixels[66] = (color)
        pixels[67] = (color)
        pixels[68] = (color)
        pixels[69] = (color)
        pixels[70] = (color)
        pixels[77] = (color)
        pixels[78] = (color)
        pixels[79] = (color)
        pixels[71] = (0, 0, 0)
        pixels[72] = (0, 0, 0)
        pixels[73] = (0, 0, 0)
        pixels[74] = (0, 0, 0)
        pixels[75] = (0, 0, 0)
        pixels[76] = (0, 0, 0)
        pixels[80] = (0, 0, 0)
        pixels[81] = (0, 0, 0)
        pixels[82] = (0, 0, 0)
        pixels[83] = (0, 0, 0)
        pixels[84] = (0, 0, 0)
        pixels[85] = (0, 0, 0)
        pixels.show()

    elif number == 8:
        pixels[65] = (color)
        pixels[66] = (color)
        pixels[67] = (color)
        pixels[68] = (color)
        pixels[69] = (color)
        pixels[70] = (color)
        pixels[71] = (color)
        pixels[72] = (color)
        pixels[73] = (color)
        pixels[74] = (color)
        pixels[75] = (color)
        pixels[76] = (color)
        pixels[77] = (color)
        pixels[78] = (color)
        pixels[79] = (color)
        pixels[80] = (color)
        pixels[81] = (color)
        pixels[82] = (color)
        pixels[83] = (color)
        pixels[84] = (color)
        pixels[85] = (color)
        pixels.show()
    
    elif number == 9:
        pixels[65] = (color)
        pixels[66] = (color)
        pixels[67] = (color)
        pixels[68] = (color)
        pixels[69] = (color)
        pixels[70] = (color)
        pixels[71] = (color)
        pixels[72] = (color)
        pixels[73] = (color)
        pixels[74] = (color)
        pixels[75] = (color)
        pixels[76] = (color)
        pixels[77] = (color)
        pixels[78] = (color)
        pixels[79] = (color)
        pixels[80] = (color)
        pixels[81] = (color)
        pixels[82] = (color)
        pixels[83] = (0, 0, 0)
        pixels[84] = (0, 0, 0)
        pixels[85] = (0, 0, 0)
        pixels.show()

# Example
# digitOne(2, (255, 0 , 0))

digit1 = 0
digit2 = 0
digit3 = 0
digit4 = 0

digitOne(digit1, (brightness))
digitTwo(digit2, (brightness))
digitThree(digit3, (brightness))
digitFour(digit4, (brightness))
pixels[42] = (brightness)
pixels[43] = (brightness)
pixels.show()

while True:

    currentTime = datetime.datetime.now()

    minutes = (currentTime.minute)
    hours = (currentTime.hour)

    # Minutes
    if minutes <= 9:
        digit1 = minutes
        digit2 = 0
    elif minutes > 9:
        string = [int(i) for i in str(minutes)]
        digit1 = (string[1])
        digit2 = (string[0])

    # Hours
    if hours <= 9:
        digit3 = hours
        digit4 = 0
    elif hours > 9:
        hours2 = hours - 12
        if hours2 == 0:
            digit3 = 2
            digit4 = 1
        elif hours2 <= 9:
            digit3 = hours2
            digit4 = 0
        elif hours2 > 9:
            string2 = [int(i) for i in str(hours2)]
            digit3 = (string2[1])
            digit4 = (string2[0])

    pixels[42] = (brightness)
    pixels[43] = (brightness)
    digitOne(digit1, (brightness))
    digitTwo(digit2, (brightness))
    digitThree(digit3, (brightness))
    digitFour(digit4, (brightness))